"""Update schema to make gender nullable

Revision ID: 4e5a4bc0cde0
Revises: 
Create Date: 2025-04-15 14:27:05.006154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5a4bc0cde0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_log', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('activity_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_log', schema=None) as batch_op:
        batch_op.alter_column('activity_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
